export const GET_BRANCHES = 'GET_BRANCHES';

export const UPDATE_SAVE_STANDARD_IN_BRANCH = 'UPDATE_SAVE_STANDARD_IN_BRANCH';

export const UPDATE_UNSAVE_STANDARD_IN_BRANCH = 'UPDATE_UNSAVE_STANDARD_IN_BRANCH';

export const SELECT_EXAM = 'SELECT_EXAM';

export const DESELECT_EXAM = 'DESELECT_EXAM';