export const GET_SAVED_STANDARDS = 'GET_SAVED_STANDARDS';

export const GET_SAVED_QUESTIONS = 'GET_SAVED_QUESTIONS';

export const UPDATE_SAVE_STANDARD = 'UPDATE_SAVE_STANDARD';

export const UPDATE_UNSAVE_STANDARD = 'UPDATE_UNSAVE_STANDARD';